name: "jmadler/git-subtree-action"
description: "Run a git subtree command in a given repository"
inputs:
  github_token:
    description: "Token"
    required: true
  git_name:
    description: "Git User Name"
    required: false
  git_email:
    description: "Git User Email"
    required: false
  repo:
    description: "Repository"
    required: false
    default: ""
  action:
    description: "Action"
    required: true
  position:
    description: "Branch, Commit, Ref, or Refspec"
    required: false
    default: ""
  prefix:
    description: "Prefix"
    required: true
  force:
    description: "Force the action"
    required: false
    default: "false"
  squash:
    description: "Squash the merge"
    required: false
    default: "false"
  message:
    description: "Message"
    required: false
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: share-2
  color: blue
